apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: main-container
    image: myorg/myapp:latest
    ports:
    - containerPort: 8000
    env:
      - name: DATABASE_URL
        value: postgres://user:password@postgres:5432/myappdb
  - name: sidecar-container
    image: busybox
    command: ['sh', '-c', 'echo "Hello from the sidecar container"']
